import { useEffect, useState } from 'react';
import apiClient from '../shared/api_client';
import FeedbackCard from '../shared/feedback_card';
import { getApiErrorMessage } from '../shared/api_error_message';

interface StaffUser { id:number;email:string;full_name:string;role:string;is_active:boolean; }
interface ManagedDriver { id:number;name:string;license_number:string;fleet_manager_id:number|null; }

export default function AdminPage(){
  const [users,setUsers]=useState<StaffUser[]>([]);
  const [feedback,setFeedback]=useState('');
  const [drivers,setDrivers]=useState<ManagedDriver[]>([]);
  const [form,setForm]=useState({full_name:'',email:'',password:'',role:'fleet_manager'});
  const loadData=()=>Promise.all([apiClient.get('/admin/users'),apiClient.get('/drivers')]).then(([userResponse,driverResponse])=>{setUsers(userResponse.data);setDrivers(driverResponse.data);}).catch(error=>setFeedback(getApiErrorMessage(error,'Administration data could not be loaded.')));
  useEffect(()=>{loadData();},[]);
  const createUser=async(event:React.FormEvent)=>{event.preventDefault();try{await apiClient.post('/admin/users',form);setForm({full_name:'',email:'',password:'',role:'fleet_manager'});loadData();}catch(error){setFeedback(getApiErrorMessage(error,'User could not be created.'));}};
  const toggleUser=async(user:StaffUser)=>{try{await apiClient.patch(`/admin/users/${user.id}/active`,null,{params:{is_active:!user.is_active}});loadData();}catch(error){setFeedback(getApiErrorMessage(error,'User status could not be changed.'));}};
  const assignManager=async(driverId:number,fleetManagerId:string)=>{if(!fleetManagerId)return;try{await apiClient.patch(`/admin/drivers/${driverId}/fleet-manager`,{fleet_manager_id:+fleetManagerId});loadData();}catch(error){setFeedback(getApiErrorMessage(error,'Driver could not be reassigned.'));}};
  const fleetManagers=users.filter(user=>user.role==='fleet_manager'&&user.is_active);
  return <><div className="topbar"><h2 className="topbar-title">User Administration</h2></div><div className="page-content"><FeedbackCard message={feedback} onDismiss={()=>setFeedback('')}/><div className="card mb-6"><h3 className="card-title mb-4">Create Staff User</h3><form onSubmit={createUser}><div className="form-row"><div className="form-group"><label className="form-label">Full name</label><input className="form-input" value={form.full_name} onChange={event=>setForm({...form,full_name:event.target.value})} required/></div><div className="form-group"><label className="form-label">Email</label><input className="form-input" type="email" value={form.email} onChange={event=>setForm({...form,email:event.target.value})} required/></div></div><div className="form-row"><div className="form-group"><label className="form-label">Temporary password</label><input className="form-input" type="password" minLength={8} value={form.password} onChange={event=>setForm({...form,password:event.target.value})} required/></div><div className="form-group"><label className="form-label">Role</label><select className="form-select" value={form.role} onChange={event=>setForm({...form,role:event.target.value})}><option value="fleet_manager">Fleet Manager</option><option value="safety_officer">Safety Officer</option><option value="financial_analyst">Financial Analyst</option></select></div></div><button className="button button-primary">Create User</button></form></div><div className="card mb-6"><h3 className="card-title mb-4">Staff Accounts</h3><div className="data-table-container"><table className="data-table"><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Action</th></tr></thead><tbody>{users.map(user=><tr key={user.id}><td>{user.full_name}</td><td>{user.email}</td><td>{user.role.replaceAll('_',' ')}</td><td><span className={`status-badge ${user.is_active?'status-badge-available':'status-badge-suspended'}`}>{user.is_active?'Active':'Deactivated'}</span></td><td><button className={`button button-small ${user.is_active?'button-danger':'button-secondary'}`} onClick={()=>toggleUser(user)}>{user.is_active?'Deactivate':'Reactivate'}</button></td></tr>)}</tbody></table></div></div><div className="card"><h3 className="card-title mb-4">Driver Ownership</h3><div className="data-table-container"><table className="data-table"><thead><tr><th>Driver</th><th>License</th><th>Fleet Manager</th></tr></thead><tbody>{drivers.map(driver=><tr key={driver.id}><td>{driver.name}</td><td>{driver.license_number}</td><td><select className="form-select" value={driver.fleet_manager_id??''} onChange={event=>assignManager(driver.id,event.target.value)}><option value="">Unassigned</option>{fleetManagers.map(manager=><option key={manager.id} value={manager.id}>{manager.full_name}</option>)}</select></td></tr>)}</tbody></table></div></div></div></>;
}
