import { useEffect, useState } from 'react';
import apiClient from '../shared/api_client';
import { useAuth } from '../shared/auth_context';
import FeedbackCard from '../shared/feedback_card';
import { getApiErrorMessage } from '../shared/api_error_message';

interface Vehicle {id:number;registration_number:string;name_model:string}
interface VehicleDocument {id:number;vehicle_id:number;vehicle_registration_number:string|null;document_type:string;file_name:string;content_type:string;expiry_date:string|null;created_at:string}

export default function VehicleDocumentsPage(){
  const {user}=useAuth(); const [documents,setDocuments]=useState<VehicleDocument[]>([]); const [vehicles,setVehicles]=useState<Vehicle[]>([]); const [feedback,setFeedback]=useState(''); const [showForm,setShowForm]=useState(false); const [file,setFile]=useState<File|null>(null); const [form,setForm]=useState({vehicle_id:'',document_type:'',expiry_date:''});
  const canWrite=user?.role==='fleet_manager'||user?.role==='safety_officer';
  const load=()=>Promise.all([apiClient.get('/vehicle-documents'),apiClient.get('/vehicles')]).then(([d,v])=>{setDocuments(d.data);setVehicles(v.data);}).catch(error=>setFeedback(getApiErrorMessage(error,'Vehicle documents could not be loaded.')));
  useEffect(()=>{void load();},[]);
  const upload=async(event:React.FormEvent)=>{event.preventDefault();if(!file)return;const payload=new FormData();payload.append('vehicle_id',form.vehicle_id);payload.append('document_type',form.document_type);if(form.expiry_date)payload.append('expiry_date',form.expiry_date);payload.append('document',file);try{await apiClient.post('/vehicle-documents',payload);setForm({vehicle_id:'',document_type:'',expiry_date:''});setFile(null);setShowForm(false);setFeedback('Vehicle document uploaded successfully.');await load();}catch(error){setFeedback(getApiErrorMessage(error,'Vehicle document could not be uploaded.'));}};
  const download=async(document:VehicleDocument)=>{try{const response=await apiClient.get(`/vehicle-documents/${document.id}/download`,{responseType:'blob'});const url=URL.createObjectURL(response.data);const link=window.document.createElement('a');link.href=url;link.download=document.file_name;link.click();URL.revokeObjectURL(url);}catch(error){setFeedback(getApiErrorMessage(error,'Vehicle document could not be downloaded.'));}};
  const remove=async(id:number)=>{try{await apiClient.delete(`/vehicle-documents/${id}`);setFeedback('Vehicle document deleted.');await load();}catch(error){setFeedback(getApiErrorMessage(error,'Vehicle document could not be deleted.'));}};
  return <><div className="topbar"><h2 className="topbar-title">Vehicle Documents</h2>{canWrite&&<button className="button button-primary" onClick={()=>setShowForm(value=>!value)}>+ Upload Document</button>}</div><div className="page-content"><FeedbackCard message={feedback} onDismiss={()=>setFeedback('')}/>{showForm&&<div className="card mb-6"><h3 className="card-title mb-4">Upload Vehicle Document</h3><form onSubmit={upload}><div className="form-row"><div className="form-group"><label className="form-label">Vehicle</label><select className="form-select" required value={form.vehicle_id} onChange={e=>setForm({...form,vehicle_id:e.target.value})}><option value="">Select vehicle...</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.registration_number} — {v.name_model}</option>)}</select></div><div className="form-group"><label className="form-label">Document Type</label><input className="form-input" required placeholder="Insurance, permit, registration..." value={form.document_type} onChange={e=>setForm({...form,document_type:e.target.value})}/></div><div className="form-group"><label className="form-label">Expiry (optional)</label><input className="form-input" type="date" value={form.expiry_date} onChange={e=>setForm({...form,expiry_date:e.target.value})}/></div></div><div className="form-group"><label className="form-label">PDF, PNG or JPEG (max 5 MB)</label><input className="form-input" type="file" accept="application/pdf,image/png,image/jpeg" required onChange={e=>setFile(e.target.files?.[0]??null)}/></div><button className="button button-primary">Upload</button> <button type="button" className="button button-secondary" onClick={()=>setShowForm(false)}>Cancel</button></form></div>}<div className="card"><div className="data-table-container"><table className="data-table"><thead><tr><th>Vehicle</th><th>Type</th><th>File</th><th>Expiry</th><th>Uploaded</th><th>Actions</th></tr></thead><tbody>{documents.map(d=><tr key={d.id}><td>{d.vehicle_registration_number||`#${d.vehicle_id}`}</td><td>{d.document_type}</td><td>{d.file_name}</td><td>{d.expiry_date||'—'}</td><td>{new Date(d.created_at).toLocaleDateString()}</td><td><div className="table-actions"><button className="button button-small button-secondary" onClick={()=>download(d)}>Download</button>{canWrite&&<button className="button button-small button-danger" onClick={()=>remove(d.id)}>Delete</button>}</div></td></tr>)}{documents.length===0&&<tr><td colSpan={6} className="data-table-empty">No vehicle documents uploaded</td></tr>}</tbody></table></div></div></div></>;
}
